# Generated by Django 5.2.1 on 2025-06-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_remove_comment_email_remove_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='service',
            field=models.ForeignKey(blank=True, help_text='اختر خدمة مرتبطة بالمقال، أو اتركه فارغ ليكون المقال عام', null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.service'),
        ),
    ]
