# Generated by Django 5.2.1 on 2025-06-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='service',
        ),
    ]
