# Generated by Django 5.2.1 on 2025-06-20 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_remove_post_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='service',
            field=models.ForeignKey(blank=True, help_text='اختر خدمة مرتبطة بالمقال، أو اتركه فارغ ليكون المقال عام', null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.service'),
        ),
    ]
