# Generated by Django 5.2.1 on 2025-06-21 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0008_alter_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField(default=False, help_text='اختر إذا كنت لا تريد عرض اسمك')),
                ('reason', models.CharField(choices=[('packing', 'تغليف ممتاز'), ('delivery', 'توصيل سريع'), ('price', 'أسعار مناسبة'), ('support', 'خدمة عملاء ممتازة'), ('other', 'أخرى')], max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقييم')),
                ('content', models.TextField(verbose_name='محتوى التقييم')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviewers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
